development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: postgres_test

production:
  <<: *default
  database: db/production.sqlite3
